name: Vulnerability Scanning
description: A custom GitHub Action
branding:
  icon: chevron-up
  color: blue
runs:
  using: "composite"
  steps:
    - run: cd $GITHUB_WORKSPACE &&
           git clone https://github.com/geekNero/vulnerability-scanning.git &&
           cd vulnerability-scanning &&
           mkdir actions
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: python -m pip install --upgrade pip &&
           pip install -r vulnerability-scanning/requirements.txt
      shell: bash
    - uses: actions/checkout@v3
      with:
        path: 'testing-actions/actions/'
    - name: Vulnerability Scanning
      run: cd $GITHUB_WORKSPACE && cd vulnerability-scanning && python3 main.py
      shell: bash